In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
import pandas as pd
import tensorflow as tf

# Import our input dataset
attrition_df = pd.read_csv('./Resources/HR-Employee-Attrition.csv')
attrition_df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [2]:
# Generate our categorical variable list
attrition_cat = attrition_df.dtypes[attrition_df.dtypes == "object"].index.tolist()

In [3]:
# Check the number of unique values in each column
attrition_df[attrition_cat].nunique()

Attrition         2
BusinessTravel    3
Department        3
EducationField    6
Gender            2
JobRole           9
MaritalStatus     3
Over18            1
OverTime          2
dtype: int64

In [4]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

# Fit and transform the OneHotEncoder using the categorical variable list
encode_df = pd.DataFrame(enc.fit_transform(attrition_df[attrition_cat]))

# Add the encoded variable names to the DataFrame
encode_df.columns = enc.get_feature_names(attrition_cat)
encode_df.head()

C:\Users\kidas\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,Attrition_No,Attrition_Yes,BusinessTravel_Non-Travel,BusinessTravel_Travel_Frequently,BusinessTravel_Travel_Rarely,Department_Human Resources,Department_Research & Development,Department_Sales,EducationField_Human Resources,EducationField_Life Sciences,...,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Over18_Y,OverTime_No,OverTime_Yes
0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
1,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
2,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
3,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
4,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0

In [5]:
# Merge one-hot encoded features and drop the originals
attrition_df = attrition_df.merge(encode_df,left_index=True, right_index=True)
attrition_df = attrition_df.drop(attrition_cat,1)
attrition_df.head()

C:\Users\kidas\AppData\Local\Temp\ipykernel_111628\1667322014.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  attrition_df = attrition_df.drop(attrition_cat,1)

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Over18_Y,OverTime_No,OverTime_Yes
0,41,1102,1,2,1,1,2,94,3,2,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
1,49,279,8,1,1,2,3,61,2,2,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
2,37,1373,2,2,1,4,4,92,2,1,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
3,33,1392,3,4,1,5,4,56,3,1,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
4,27,591,2,1,1,7,1,40,3,1,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0

In [6]:
#Split our preprocessed data into our features and target arrays
y = attrition_df["Attrition_Yes"].values
X = attrition_df.drop(["Attrition_Yes","Attrition_No"],1).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

C:\Users\kidas\AppData\Local\Temp\ipykernel_111628\7982933.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  X = attrition_df.drop(["Attrition_Yes","Attrition_No"],1).values

In [7]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [8]:
# Define the model - deep neural net
number_input_features = len(X_train[0])
hidden_nodes_layer1 = 8
hidden_nodes_layer2 = 5

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 8)                 448

 dense_1 (Dense)             (None, 5)                 45

 dense_2 (Dense)             (None, 1)                 6

=================================================================
Total params: 499
Trainable params: 499
Non-trainable params: 0
_________________________________________________________________

In [9]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [10]:
# Train the model
fit_model = nn.fit(X_train,y_train,epochs=100)

Epoch 1/100
35/35 [==============================] - 2s 3ms/step - loss: 304.7873 - accuracy: 0.6633
Epoch 2/100
35/35 [==============================] - 0s 3ms/step - loss: 110.4942 - accuracy: 0.6679
Epoch 3/100
35/35 [==============================] - 0s 2ms/step - loss: 48.1898 - accuracy: 0.6606
Epoch 4/100
35/35 [==============================] - 0s 2ms/step - loss: 22.4402 - accuracy: 0.7060
Epoch 5/100
35/35 [==============================] - 0s 3ms/step - loss: 9.7375 - accuracy: 0.7223
Epoch 6/100
35/35 [==============================] - 0s 2ms/step - loss: 5.6789 - accuracy: 0.7396
Epoch 7/100
35/35 [==============================] - 0s 3ms/step - loss: 4.3764 - accuracy: 0.7505
Epoch 8/100
35/35 [==============================] - 0s 3ms/step - loss: 3.3503 - accuracy: 0.7505
Epoch 9/100
35/35 [==============================] - 0s 2ms/step - loss: 3.1567 - accuracy: 0.7550
Epoch 10/100
35/35 [==============================] - 0s 3ms/step - loss: 2.1023 - accuracy: 0.7387
Epoch 11/100
35/35 [==============================] - 0s 2ms/step - loss: 1.6820 - accuracy: 0.7650
Epoch 12/100
35/35 [==============================] - 0s 2ms/step - loss: 1.6058 - accuracy: 0.7350
Epoch 13/100
35/35 [==============================] - 0s 2ms/step - loss: 2.2721 - accuracy: 0.7368
Epoch 14/100
35/35 [==============================] - 0s 2ms/step - loss: 1.3601 - accuracy: 0.7359
Epoch 15/100
35/35 [==============================] - 0s 2ms/step - loss: 1.2241 - accuracy: 0.7441
Epoch 16/100
35/35 [==============================] - 0s 3ms/step - loss: 1.4688 - accuracy: 0.7523
Epoch 17/100
35/35 [==============================] - 0s 3ms/step - loss: 0.9048 - accuracy: 0.7731
Epoch 18/100
35/35 [==============================] - 0s 3ms/step - loss: 1.2366 - accuracy: 0.7359
Epoch 19/100
35/35 [==============================] - 0s 3ms/step - loss: 1.4944 - accuracy: 0.7132
Epoch 20/100
35/35 [==============================] - 0s 3ms/step - loss: 1.0628 - accuracy: 0.7532
Epoch 21/100
35/35 [==============================] - 0s 3ms/step - loss: 0.8866 - accuracy: 0.7650
Epoch 22/100
35/35 [==============================] - 0s 3ms/step - loss: 0.7635 - accuracy: 0.7813
Epoch 23/100
35/35 [==============================] - 0s 2ms/step - loss: 0.7756 - accuracy: 0.7704
Epoch 24/100
35/35 [==============================] - 0s 2ms/step - loss: 0.7211 - accuracy: 0.7750
Epoch 25/100
35/35 [==============================] - 0s 2ms/step - loss: 0.7197 - accuracy: 0.7804
Epoch 26/100
35/35 [==============================] - 0s 2ms/step - loss: 0.8205 - accuracy: 0.7613
Epoch 27/100
35/35 [==============================] - 0s 3ms/step - loss: 0.6898 - accuracy: 0.7659
Epoch 28/100
35/35 [==============================] - 0s 3ms/step - loss: 0.6085 - accuracy: 0.7822
Epoch 29/100
35/35 [==============================] - 0s 3ms/step - loss: 1.3115 - accuracy: 0.7278
Epoch 30/100
35/35 [==============================] - 0s 2ms/step - loss: 0.7628 - accuracy: 0.7586
Epoch 31/100
35/35 [==============================] - 0s 2ms/step - loss: 0.6542 - accuracy: 0.7759
Epoch 32/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5844 - accuracy: 0.7731
Epoch 33/100
35/35 [==============================] - 0s 2ms/step - loss: 0.7309 - accuracy: 0.7704
Epoch 34/100
35/35 [==============================] - 0s 2ms/step - loss: 1.7992 - accuracy: 0.7296
Epoch 35/100
35/35 [==============================] - 0s 2ms/step - loss: 1.0824 - accuracy: 0.7432
Epoch 36/100
35/35 [==============================] - 0s 2ms/step - loss: 0.6621 - accuracy: 0.7768
Epoch 37/100
35/35 [==============================] - 0s 2ms/step - loss: 1.2120 - accuracy: 0.7541
Epoch 38/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5055 - accuracy: 0.7949
Epoch 39/100
35/35 [==============================] - 0s 2ms/step - loss: 0.7949 - accuracy: 0.7813
Epoch 40/100
35/35 [==============================] - 0s 2ms/step - loss: 0.7633 - accuracy: 0.7650
Epoch 41/100
35/35 [==============================] - 0s 3ms/step - loss: 0.7705 - accuracy: 0.7686
Epoch 42/100
35/35 [==============================] - 0s 2ms/step - loss: 0.8783 - accuracy: 0.7414
Epoch 43/100
35/35 [==============================] - 0s 3ms/step - loss: 0.5839 - accuracy: 0.7886
Epoch 44/100
35/35 [==============================] - 0s 4ms/step - loss: 0.6819 - accuracy: 0.7586
Epoch 45/100
35/35 [==============================] - 0s 6ms/step - loss: 0.7958 - accuracy: 0.7577
Epoch 46/100
35/35 [==============================] - 0s 3ms/step - loss: 0.5241 - accuracy: 0.7995
Epoch 47/100
35/35 [==============================] - 0s 2ms/step - loss: 0.6900 - accuracy: 0.7813
Epoch 48/100
35/35 [==============================] - 0s 2ms/step - loss: 0.7070 - accuracy: 0.7568
Epoch 49/100
35/35 [==============================] - 0s 2ms/step - loss: 1.5036 - accuracy: 0.7269
Epoch 50/100
35/35 [==============================] - 0s 2ms/step - loss: 0.7833 - accuracy: 0.7613
Epoch 51/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5668 - accuracy: 0.7985
Epoch 52/100
35/35 [==============================] - 0s 2ms/step - loss: 0.6199 - accuracy: 0.7913
Epoch 53/100
35/35 [==============================] - 0s 2ms/step - loss: 0.9117 - accuracy: 0.7505
Epoch 54/100
35/35 [==============================] - 0s 2ms/step - loss: 0.8193 - accuracy: 0.7387
Epoch 55/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5067 - accuracy: 0.7940
Epoch 56/100
35/35 [==============================] - 0s 3ms/step - loss: 0.4860 - accuracy: 0.8103
Epoch 57/100
35/35 [==============================] - 0s 3ms/step - loss: 0.5528 - accuracy: 0.7958
Epoch 58/100
35/35 [==============================] - 0s 3ms/step - loss: 0.6123 - accuracy: 0.7949
Epoch 59/100
35/35 [==============================] - 0s 3ms/step - loss: 0.5517 - accuracy: 0.7967
Epoch 60/100
35/35 [==============================] - 0s 3ms/step - loss: 0.6803 - accuracy: 0.7777
Epoch 61/100
35/35 [==============================] - 0s 3ms/step - loss: 0.5776 - accuracy: 0.8022
Epoch 62/100
35/35 [==============================] - 0s 3ms/step - loss: 0.5525 - accuracy: 0.8076
Epoch 63/100
35/35 [==============================] - 0s 2ms/step - loss: 0.6231 - accuracy: 0.7904
Epoch 64/100
35/35 [==============================] - 0s 3ms/step - loss: 1.2119 - accuracy: 0.7323
Epoch 65/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5514 - accuracy: 0.8004
Epoch 66/100
35/35 [==============================] - 0s 2ms/step - loss: 0.4894 - accuracy: 0.8167
Epoch 67/100
35/35 [==============================] - 0s 3ms/step - loss: 0.5386 - accuracy: 0.8058
Epoch 68/100
35/35 [==============================] - 0s 2ms/step - loss: 0.7182 - accuracy: 0.7777
Epoch 69/100
35/35 [==============================] - 0s 2ms/step - loss: 0.9695 - accuracy: 0.7668
Epoch 70/100
35/35 [==============================] - 0s 2ms/step - loss: 0.4910 - accuracy: 0.8013
Epoch 71/100
35/35 [==============================] - 0s 2ms/step - loss: 1.1435 - accuracy: 0.7505
Epoch 72/100
35/35 [==============================] - 0s 2ms/step - loss: 0.6584 - accuracy: 0.7604
Epoch 73/100
35/35 [==============================] - 0s 2ms/step - loss: 0.6020 - accuracy: 0.7985
Epoch 74/100
35/35 [==============================] - 0s 2ms/step - loss: 0.6187 - accuracy: 0.7877
Epoch 75/100
35/35 [==============================] - 0s 2ms/step - loss: 0.9884 - accuracy: 0.7750
Epoch 76/100
35/35 [==============================] - 0s 3ms/step - loss: 0.8930 - accuracy: 0.7659
Epoch 77/100
35/35 [==============================] - 0s 3ms/step - loss: 0.7452 - accuracy: 0.7740
Epoch 78/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5230 - accuracy: 0.8031
Epoch 79/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5244 - accuracy: 0.7976
Epoch 80/100
35/35 [==============================] - 0s 2ms/step - loss: 0.6122 - accuracy: 0.7822
Epoch 81/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5241 - accuracy: 0.7940
Epoch 82/100
35/35 [==============================] - 0s 3ms/step - loss: 0.9209 - accuracy: 0.7523

Epoch 83/100
35/35 [==============================] - 0s 2ms/step - loss: 0.7076 - accuracy: 0.7713
Epoch 84/100
35/35 [==============================] - 0s 2ms/step - loss: 0.4526 - accuracy: 0.8221
Epoch 85/100
35/35 [==============================] - 0s 2ms/step - loss: 0.4671 - accuracy: 0.8249
Epoch 86/100
35/35 [==============================] - 0s 2ms/step - loss: 0.4450 - accuracy: 0.8194
Epoch 87/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5653 - accuracy: 0.7976
Epoch 88/100
35/35 [==============================] - 0s 2ms/step - loss: 0.6895 - accuracy: 0.7768
Epoch 89/100
35/35 [==============================] - 0s 2ms/step - loss: 0.4978 - accuracy: 0.8122
Epoch 90/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5304 - accuracy: 0.8094
Epoch 91/100
35/35 [==============================] - 0s 3ms/step - loss: 0.4958 - accuracy: 0.7995
Epoch 92/100
35/35 [==============================] - 0s 2ms/step - loss: 0.4556 - accuracy: 0.7995
Epoch 93/100
35/35 [==============================] - 0s 2ms/step - loss: 0.4875 - accuracy: 0.8131
Epoch 94/100
35/35 [==============================] - 0s 2ms/step - loss: 0.6130 - accuracy: 0.7786
Epoch 95/100
35/35 [==============================] - 0s 2ms/step - loss: 0.6256 - accuracy: 0.7858
Epoch 96/100
35/35 [==============================] - 0s 2ms/step - loss: 0.9820 - accuracy: 0.7659
Epoch 97/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5679 - accuracy: 0.8004
Epoch 98/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5915 - accuracy: 0.8004
Epoch 99/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5385 - accuracy: 0.8076
Epoch 100/100
35/35 [==============================] - 0s 3ms/step - loss: 0.4754 - accuracy: 0.8258

In [11]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

12/12 - 0s - loss: 0.9842 - accuracy: 0.8614 - 343ms/epoch - 29ms/step
Loss: 0.9842057228088379, Accuracy: 0.8614130616188049

## Random Forest Vs. Deep Learning Model

In [12]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import OneHotEncoder
import pandas as pd
import tensorflow as tf

# Import our input dataset
loans_df = pd.read_csv('./Resources/loan_status.csv')
loans_df.head()

,Loan_Status,Current_Loan_Amount,Term,Credit_Score,Annual_Income,Years_in_current_job,Home_Ownership,Purpose,Monthly_Debt,Years_of_Credit_History,Months_since_last_delinquent,Number_of_Open_Accounts,Number_of_Credit_Problems,Current_Credit_Balance,Maximum_Open_Credit,Bankruptcies,Tax_Liens
0,Fully_Paid,99999999,Short_Term,741.0,2231892.0,8_years,Own_Home,Debt_Consolidation,29200.53,14.9,29.0,18,1,297996,750090.0,0.0,0.0
1,Fully_Paid,217646,Short_Term,730.0,1184194.0,<_1_year,Home_Mortgage,Debt_Consolidation,10855.08,19.6,10.0,13,1,122170,272052.0,1.0,0.0
2,Fully_Paid,548746,Short_Term,678.0,2559110.0,2_years,Rent,Debt_Consolidation,18660.28,22.6,33.0,4,0,437171,555038.0,0.0,0.0
3,Fully_Paid,99999999,Short_Term,728.0,714628.0,3_years,Rent,Debt_Consolidation,11851.06,16.0,76.0,16,0,203965,289784.0,0.0,0.0
4,Fully_Paid,99999999,Short_Term,740.0,776188.0,<_1_year,Own_Home,Debt_Consolidation,11578.22,8.5,25.0,6,0,134083,220220.0,0.0,0.0

In [13]:
# Generate our categorical variable list
loans_cat = loans_df.dtypes[loans_df.dtypes == "object"].index.tolist()

# Check the number of unique values in each column
loans_df[loans_cat].nunique()

Loan_Status              2
Term                     2
Years_in_current_job    11
Home_Ownership           4
Purpose                  7
dtype: int64

In [14]:
# Check the unique value counts to see if binning is required
loans_df.Years_in_current_job.value_counts()

10+_years    13149
2_years       3225
3_years       2997
<_1_year      2699
5_years       2487
4_years       2286
1_year        2247
6_years       2109
7_years       2082
8_years       1675
9_years       1467
Name: Years_in_current_job, dtype: int64

In [15]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

# Fit and transform the OneHotEncoder using the categorical variable list
encode_df = pd.DataFrame(enc.fit_transform(loans_df[loans_cat]))

# Add the encoded variable names to the DataFrame
encode_df.columns = enc.get_feature_names(loans_cat)
encode_df.head()

C:\Users\kidas\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,Loan_Status_Fully_Paid,Loan_Status_Not_Paid,Term_Long_Term,Term_Short_Term,Years_in_current_job_10+_years,Years_in_current_job_1_year,Years_in_current_job_2_years,Years_in_current_job_3_years,Years_in_current_job_4_years,Years_in_current_job_5_years,...,Home_Ownership_Home_Mortgage,Home_Ownership_Own_Home,Home_Ownership_Rent,Purpose_Business_Loan,Purpose_Buy_House,Purpose_Buy_a_Car,Purpose_Debt_Consolidation,Purpose_Home_Improvements,Purpose_Medical_Bills,Purpose_Other
0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [16]:
# Merge one-hot encoded features and drop the originals
loans_df = loans_df.merge(encode_df,left_index=True, right_index=True)
loans_df = loans_df.drop(loans_cat,1)
loans_df.head()

C:\Users\kidas\AppData\Local\Temp\ipykernel_111628\1908271011.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  loans_df = loans_df.drop(loans_cat,1)

,Current_Loan_Amount,Credit_Score,Annual_Income,Monthly_Debt,Years_of_Credit_History,Months_since_last_delinquent,Number_of_Open_Accounts,Number_of_Credit_Problems,Current_Credit_Balance,Maximum_Open_Credit,...,Home_Ownership_Home_Mortgage,Home_Ownership_Own_Home,Home_Ownership_Rent,Purpose_Business_Loan,Purpose_Buy_House,Purpose_Buy_a_Car,Purpose_Debt_Consolidation,Purpose_Home_Improvements,Purpose_Medical_Bills,Purpose_Other
0,99999999,741.0,2231892.0,29200.53,14.9,29.0,18,1,297996,750090.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,217646,730.0,1184194.0,10855.08,19.6,10.0,13,1,122170,272052.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,548746,678.0,2559110.0,18660.28,22.6,33.0,4,0,437171,555038.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,99999999,728.0,714628.0,11851.06,16.0,76.0,16,0,203965,289784.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,99999999,740.0,776188.0,11578.22,8.5,25.0,6,0,134083,220220.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [17]:
# Remove loan status target from features data
y = loans_df.Loan_Status_Fully_Paid
X = loans_df.drop(columns=["Loan_Status_Fully_Paid","Loan_Status_Not_Paid"])

# Split training/test datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, stratify=y)

# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [18]:
# Create a random forest classifier.
rf_model = RandomForestClassifier(n_estimators=128, random_state=78)

# Fitting the model
rf_model = rf_model.fit(X_train_scaled, y_train)

# Evaluate the model
y_pred = rf_model.predict(X_test_scaled)
print(f" Random forest predictive accuracy: {accuracy_score(y_test,y_pred):.3f}")

 Random forest predictive accuracy: 0.849

In [19]:
# Define the model - deep neural net
number_input_features = len(X_train_scaled[0])
hidden_nodes_layer1 = 24
hidden_nodes_layer2 = 12

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))


# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Compile the Sequential model together and customize metrics
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=50)

# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Epoch 1/50
854/854 [==============================] - 3s 2ms/step - loss: 0.4449 - accuracy: 0.8215
Epoch 2/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3880 - accuracy: 0.8488
Epoch 3/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3831 - accuracy: 0.8487
Epoch 4/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3808 - accuracy: 0.8494
Epoch 5/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3792 - accuracy: 0.8492
Epoch 6/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3780 - accuracy: 0.8497
Epoch 7/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3771 - accuracy: 0.8497
Epoch 8/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3764 - accuracy: 0.8495
Epoch 9/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3755 - accuracy: 0.8499
Epoch 10/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3748 - accuracy: 0.8497
Epoch 11/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3738 - accuracy: 0.8500
Epoch 12/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3735 - accuracy: 0.8499
Epoch 13/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3727 - accuracy: 0.8505
Epoch 14/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3720 - accuracy: 0.8502
Epoch 15/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3715 - accuracy: 0.8506
Epoch 16/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3709 - accuracy: 0.8503
Epoch 17/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3703 - accuracy: 0.8504
Epoch 18/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3698 - accuracy: 0.8504
Epoch 19/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3694 - accuracy: 0.8502
Epoch 20/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3691 - accuracy: 0.8509
Epoch 21/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3684 - accuracy: 0.8513
Epoch 22/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3678 - accuracy: 0.8515
Epoch 23/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3674 - accuracy: 0.8511
Epoch 24/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3668 - accuracy: 0.8516
Epoch 25/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3663 - accuracy: 0.8517
Epoch 26/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3656 - accuracy: 0.8520
Epoch 27/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3658 - accuracy: 0.8520
Epoch 28/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3652 - accuracy: 0.8518
Epoch 29/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3650 - accuracy: 0.8520
Epoch 30/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3646 - accuracy: 0.8520
Epoch 31/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3641 - accuracy: 0.8526
Epoch 32/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3638 - accuracy: 0.8524
Epoch 33/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3634 - accuracy: 0.8527
Epoch 34/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3630 - accuracy: 0.8534
Epoch 35/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3629 - accuracy: 0.8530
Epoch 36/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3627 - accuracy: 0.8531
Epoch 37/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3622 - accuracy: 0.8537
Epoch 38/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3622 - accuracy: 0.8536
Epoch 39/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3619 - accuracy: 0.8531
Epoch 40/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3617 - accuracy: 0.8535
Epoch 41/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3614 - accuracy: 0.8535
Epoch 42/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3609 - accuracy: 0.8529
Epoch 43/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3607 - accuracy: 0.8532
Epoch 44/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3603 - accuracy: 0.8546
Epoch 45/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3604 - accuracy: 0.8538
Epoch 46/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3600 - accuracy: 0.8539
Epoch 47/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3601 - accuracy: 0.8540
Epoch 48/50
854/854 [==============================] - 2s 3ms/step - loss: 0.3593 - accuracy: 0.8541
Epoch 49/50
854/854 [==============================] - 2s 3ms/step - loss: 0.3593 - accuracy: 0.8540
Epoch 50/50
854/854 [==============================] - 2s 2ms/step - loss: 0.3592 - accuracy: 0.8542
285/285 - 1s - loss: 0.3959 - accuracy: 0.8432 - 858ms/epoch - 3ms/step
Loss: 0.3959147036075592, Accuracy: 0.8431802988052368

## Checkpoints Are Not Just for Video Games

In [20]:
# Import checkpoint dependencies
import os
from tensorflow.keras.callbacks import ModelCheckpoint

# Define the checkpoint path and filenames
os.makedirs("checkpoints/",exist_ok=True)
checkpoint_path = "checkpoints/weights.{epoch:02d}.hdf5"

In [ ]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

# Create a callback that saves the model's weights every epoch
cp_callback = ModelCheckpoint(
    filepath=checkpoint_path,
    verbose=1,
    save_weights_only=True,
    save_freq='epoch')

# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=100,callbacks=[cp_callback])

# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Epoch 1/100
849/854 [============================>.] - ETA: 0s - loss: 0.3591 - accuracy: 0.8544
Epoch 1: saving model to checkpoints\weights.01.hdf5
854/854 [==============================] - 3s 3ms/step - loss: 0.3591 - accuracy: 0.8544
Epoch 2/100
845/854 [============================>.] - ETA: 0s - loss: 0.3596 - accuracy: 0.8541
Epoch 2: saving model to checkpoints\weights.02.hdf5
854/854 [==============================] - 2s 2ms/step - loss: 0.3588 - accuracy: 0.8545
Epoch 3/100
851/854 [============================>.] - ETA: 0s - loss: 0.3579 - accuracy: 0.8553
Epoch 3: saving model to checkpoints\weights.03.hdf5
854/854 [==============================] - 2s 2ms/step - loss: 0.3581 - accuracy: 0.8551
Epoch 4/100
853/854 [============================>.] - ETA: 0s - loss: 0.3586 - accuracy: 0.8541
Epoch 4: saving model to checkpoints\weights.04.hdf5
854/854 [==============================] - 2s 3ms/step - loss: 0.3585 - accuracy: 0.8541
Epoch 5/100
849/854 [============================>.] - ETA: 0s - loss: 0.3577 - accuracy: 0.8540
Epoch 5: saving model to checkpoints\weights.05.hdf5
854/854 [==============================] - 2s 2ms/step - loss: 0.3577 - accuracy: 0.8540
Epoch 6/100
844/854 [============================>.] - ETA: 0s - loss: 0.3571 - accuracy: 0.8544
Epoch 6: saving model to checkpoints\weights.06.hdf5
854/854 [==============================] - 2s 2ms/step - loss: 0.3571 - accuracy: 0.8543
Epoch 7/100
837/854 [============================>.] - ETA: 0s - loss: 0.3575 - accuracy: 0.8545
Epoch 7: saving model to checkpoints\weights.07.hdf5
854/854 [==============================] - 2s 2ms/step - loss: 0.3572 - accuracy: 0.8546
Epoch 8/100
673/854 [======================>.......] - ETA: 0s - loss: 0.3573 - accuracy: 0.8539

In [ ]:
# Define the model - deep neural net
number_input_features = len(X_train_scaled[0])
hidden_nodes_layer1 = 8
hidden_nodes_layer2 = 5

nn_new = tf.keras.models.Sequential()

# First hidden layer
nn_new.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn_new.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn_new.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Compile the model
nn_new.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

# Restore the model weights
nn_new.load_weights("checkpoints/weights.100.hdf5")

# Evaluate the model using the test data
model_loss, model_accuracy = nn_new.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

In [ ]:
# Export our model to HDF5 file
nn_new.save("trained_attrition.h5")

In [ ]:
# Import the model to a new object
nn_imported = tf.keras.models.load_model('trained_attrition.h5')

In [ ]:
# Evaluate the completed model using the test data
model_loss, model_accuracy = nn_imported.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")